backend:
  name: github
  repo: mattburns/cgschoolstreet
  branch: main

media_folder: public/images
public_folder: images
collections:
  - name: "pages"
    label: "Pages"
    files:
    - label: "Home"
      name: "home"
      file: "content/home.md"
      fields:
        - { label: "Title", name: "title", widget: "string"}
        - { label: "Publish Date", name: "date", widget: "datetime" }
        - { label: "Body", name: "body", widget: "markdown"}
        - label: 'Cats'
          name: "cats"
          widget: list
          fields:
            - { label: "Name", name: "name", widget: "string"}
            - { label: "Description", name: "description", widget: "text"}
            - { label: "Body", name: "body", widget: "markdown"}
    - label: "Links"
      name: "links"
      file: "content/links.md"
      fields:
        - { label: "Title", name: "title", widget: "string"}
        - { label: "Publish Date", name: "date", widget: "datetime" }
        - { label: "Body", name: "body", widget: "markdown"}
        - label: 'Links'
          name: "links"
          widget: list
          fields:
            - { label: "Name", name: "name", widget: "string"}
            - { label: "Url", name: "url", widget: "text"}